### PR TITLE
oauthPage preferences

### PR DESCRIPTION
**Pull request by jimmyjames**
add documentation for using oauthPage option for web services preferences.

### CODE REVIEW

**Comment by unixbeast** [comment]
do you think you should call this out specifically?
"Additional pages cannot contain any inputs - only display information (e.g., for additional information, instructions, etc.)"

**Comment by jimmyjames** [comment]
Yes I think something is needed around that. More research is needed on my end to know if this is really the case, or if there's a way to make it work currently.

This will have to be separate from the ongoing questions/gaps of how the auth page handles preferences differently, including what features are planned to work, and what is not. Unfortunately given current priorities and capacity, I don't know think these questions will be answered any time soon. 

Will update this PR with updates later.

**Comment by jimmyjames** [comment]
Updated PR to include:
* basic auth preferences using single preferences page
* specifying `oauthPage` in preferences for oauth-specific preferences
* using dynamic pages for additional, non-device inputs

@llinder I'd like you to review this prior to merging, to ensure that this documentation is aligned with the intent/design/functionality of the authorization page.

**Comment by llinder** [comment]
The documentation looks correct based on my understandings of its intended use :+1:

**Pull request merged**
