### PR TITLE
Update getting-help.rst

### PR DESCRIPTION
**Pull request by tslagle13**

### CODE REVIEW

**Comment by tslagle13** [comment]
@jimmyjames @unixbeast 

Simple change but would like your 👍

**Comment by jimmyjames** [comment]
Looks good. While you're in there... is there something we can add/link to with meeting calendar links or zoom url?

**Comment by tslagle13** [comment]
Good idea. We can link to the "participate" section of the dev site

**Comment by jimmyjames** [comment]
💯

**Pull request merged**
