### PR TITLE
[DOCS-428] - document conversion methods on ColorUtilities

### PR DESCRIPTION
**Pull request by jimmyjames**
Documents the conversion methods on ColorUtilities. This does not document the color maps, as those are not yet ready for full support and documentation.

This PR is dependent on the HSV conversion methods being deployed (scheduled for the next data-management deploy).

@larsfinander can you please review?

/cc @rappleg @rajkaramchedu

### CODE REVIEW

**Comment by larsfinander** [comment]
@jimmyjames I dont think we should expose the color conversion methods to the public yet. I am not sure if we should even be using HSL at all.

**Comment by jimmyjames** [comment]
I'll follow up in an email.

**Comment by jimmyjames** [comment]
@larsfinander updated the PR to only include `hexToRgb()` and `rgbToHex()`.

**Comment by jimmyjames** [comment]
@larsfinander bump

**Comment by jimmyjames** [comment]
@larsfinander bump again, if you cannot review this please either delegate or let me know and I'll find someone else to review.

**Pull request merged**
