### PR TITLE
add SHM event information.

### PR DESCRIPTION
**Pull request by jimmyjames**
Was curious and had an hour over the weekend to try this and write up some basic docs for interacting with SHM through the location events.

Rather than sit on it I figured it best to get a PR out there now.

@bflorian I would appreciate your review before merging this - thanks in advance.

/cc @tslagle13 @unixbeast

### CODE REVIEW

**Comment by jimmyjames** [comment]
I'd like to get this merged and into our docs soon. I would appreciate some eyes on it first, however.

@bflorian @tslagle13 @unixbeast

**Comment by tslagle13** [comment]
:+1:

**Comment by jimmyjames** [comment]
Do not merge. It's been reported that getting alarm state from the location is no longer working. I need to investigate.

**Comment by jimmyjames** [comment]
Added another commit that fixes the example of how to get `alarmSystemStatus` event value.

**Comment by unixbeast** [comment]
Is this ready to go now?

**Comment by jimmyjames** [comment]
DO NOT MERGE.

There are conversations ongoing around what APIs can be publicly supported. It is likely that we can support getting SHM information, but not support setting SHM state outside of SHM itself.

I'll either close this PR pending that conversation, or update this PR and remove instructions on how to set SHM.

**Comment by jimmyjames** [comment]
Per discussion with product management, the ability for third party developers to get/control SHM is not supported. Consideration is being given to designing a way for third party developers to interact with SHM in the future.

Closing this PR.

**Pull request closed without merging**
