### PR TITLE
[DOCS-426] Adding Whats New Section

### PR DESCRIPTION
**Pull request by rajkaramchedu**
@jimmyjames See what you think of this approach? The intent is this: the "What's New" page will only focus on last changes, highlighting their benefits with a short blurb, and the docs change log is right below it for those who want to delve into details and for some history.

### CODE REVIEW

**Comment by jimmyjames** [comment]
My initial thought is that having two separate documents is somewhat confusing. I like the expanded explanations around the changes though. Any reason the change log can't be rebranded and the tone of each item is changed to be similar to what's here?

**Comment by rajkaramchedu** [comment]
That could work too. Let me see how that works.

**Comment by rajkaramchedu** [comment]
@jimmyjames made the change; and modified only the latest release text. Do you think we should modify the text for earlier releases too?

**Comment by jimmyjames** [comment]
I like the single page. I wonder if having a caption "What's New" and page titled "What's New" is a bit too redundant? What if the caption is "What's New" and the page is titled "Recent Changes"?

Regarding changing earlier releases, I think that we should change the last ~4 releases or so. No need to go all the way back, but the most recent ones I think are worth updating.

**Comment by rajkaramchedu** [comment]
@jimmyjames Just made the changes, please review.

**Comment by jimmyjames** [comment]
I like it! 👍

**Pull request merged**
