### PR TITLE
[DOCS-395] Adding "Working with Time Zones" section 

### PR DESCRIPTION
**Pull request by rajkaramchedu**

### CODE REVIEW

**Comment by jimmyjames** [comment]
Can you squash these 2 commits before merging?

**Comment by rajkaramchedu** [comment]
Let me do that.

**Comment by rajkaramchedu** [comment]
Did I squash them right?

**Comment by jimmyjames** [comment]
I still see two commits; there should be one.

**Comment by rajkaramchedu** [comment]
Okay, will fix it. Thanks!

**Comment by jimmyjames** [comment]
in this case it's probably not a big deal since one commit is just a normal merge commit. In general we want only one commit but can make an exception in this case.

**Pull request merged**
