### PR TITLE
DOCS-291 - updating the return value for /api/smartapps/endpoints

### PR DESCRIPTION
**Pull request by unixbeast**

### CODE REVIEW

**Comment by jimmyjames** [comment]
👍 to merge pending the DM deploy

**Comment by tslagle13** [comment]
Thanks guys!

**Comment by jimmyjames** [comment]
@unixbeast I think we should explain what the list of returned json objects is and why it's a list.

**Comment by unixbeast** [comment]
@llinder could you please answer the question that Jim posted in the above comment?

**Comment by llinder** [comment]
@jimmyjames correct /api/smartapps/endpoints will return a list of all installed SmartApps for the client ID associated with the given access token.

**Comment by jimmyjames** [comment]
👍 thanks guys

**Comment by iamcanadian2222** [comment]
It's officially documented as a list/array response, so that means we can use this for multi-location authorization now, right? :stuck_out_tongue_winking_eye: @625alex

**Pull request merged**
