### PR TITLE
[DOCS-314] add grails and groovy version to docs

### PR DESCRIPTION
**Pull request by jimmyjames**
Documenting the grails/groovy version used.

@Bijnagte please review

### CODE REVIEW

**Comment by Bijnagte** [comment]
I would say that I don't know that it matters to end users that we run grails since they are sandboxed away from that anyway. At some point in the not to distant future we may not be running executions from within grails at all.

**Comment by jimmyjames** [comment]
I would tend to agree, but there are certain cases where grails classes/impacts leak to the developer APIs. It's not great, but is what it is, which is why I opted to include it for transparency. I could add a note to clarify that grails isn't something that should directly impact developers to help clarify...

**Comment by Bijnagte** [comment]
Sure, I don't see any big issues then, I just am not sure we expose that we run grails anywhere officially. Looks correct to me though

**Comment by Bijnagte** [comment]
👍 once it reflects reality (grails upgrade still in progess)

**Pull request closed without merging**
